name: hotel_1
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  syncfusion_flutter_sliders: ^21.2.6
  flutter_rating_bar: ^4.0.0
  intl: ^0.18.1
  google_fonts: ^4.0.4
  table_calendar: ^3.0.9
  http: ^1.0.0
  dio: ^5.2.1+1
  flutter_screenutil: ^5.8.4
  dropdown_button2: ^2.1.3
  email_validator: ^2.1.17
  shared_preferences: ^2.1.2
  flutter_svg: ^2.0.7
  otp_text_field: ^1.1.3
  image_cropper: ^5.0.0
  image_picker: ^0.8.9
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/hotel1.jpeg
    - assets/images/hotel2.jpeg
    - assets/images/hotel3.jpeg
    - assets/images/hotel4.jpeg
    - assets/images/hotel5.jpeg
    - assets/images/hotel6.jpeg
    - assets/images/search1.jpeg
    - assets/images/flagID.jpeg
    - assets/images/flagSG.jpeg
    - assets/images/flagMY.jpeg
    - assets/images/flagTH.jpeg
    - assets/images/detail_h1.jpeg
    - assets/images/detail_h2.jpeg
    - assets/images/detail_h3.jpeg
    - assets/images/vector.jpeg
    - assets/images/VA.jpeg
    - assets/images/OVO.jpeg
    - assets/images/Gopay.jpeg
    - assets/images/Minimarket.jpeg
    - assets/images/Hotel.jpeg
    - assets/images/BCA.jpeg
    - assets/images/BRI.jpeg
    - assets/images/MANDIRI.jpeg
    - assets/images/CC.jpeg
    - assets/images/indomaret.png
    - assets/images/alfamart.png
    - assets/images/verified.jpeg
    - assets/images/type.jpeg
    - assets/images/detail_k1.jpeg
    - assets/images/detail_k2.jpeg
    - assets/images/detail_k3.jpeg
