name: capstone_project_tripease
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  buttons_tabbar: ^1.3.6
  contained_tab_bar_view: ^0.8.0
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.8.2
  flutter_svg: ^2.0.6
  google_fonts: ^4.0.4
  http: ^1.0.0
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  timer_builder: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
