name: hotel_1
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  email_validator: ^2.1.17
  flutter_screenutil: ^5.8.2
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  otp_text_field: ^1.1.3
  image_cropper: ^4.0.1
  image_picker: ^0.8.5+3
  table_calendar: ^3.0.9
  flutter_rating_bar: ^4.0.1
  flutter_datetime_picker: ^1.5.1
  shared_preferences: ^2.1.1
  dropdown_button2: ^2.1.2
  dio: ^5.1.2
  provider: ^6.0.5
  flutter_localization: ^0.1.11
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  get: ^4.6.5
  qr_flutter: ^4.1.0
  random_string: ^2.3.1

  cupertino_icons: ^1.0.2

  syncfusion_flutter_sliders: ^21.2.6

  http: ^0.13.4

  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/hotel1.jpeg
    - assets/images/hotel2.jpeg
    - assets/images/hotel3.jpeg
    - assets/images/hotel4.jpeg
    - assets/images/hotel5.jpeg
    - assets/images/hotel6.jpeg
    - assets/images/search1.jpeg
    - assets/images/flagID.jpeg
    - assets/images/flagSG.jpeg
    - assets/images/flagMY.jpeg
    - assets/images/flagTH.jpeg
    - assets/images/detail_h1.jpeg
    - assets/images/detail_h2.jpeg
    - assets/images/detail_h3.jpeg
    - assets/images/vector.jpeg
    - assets/images/VA.jpeg
    - assets/images/OVO.jpeg
    - assets/images/Gopay.jpeg
    - assets/images/Minimarket.jpeg
    - assets/images/Hotel.jpeg
    - assets/images/BCA.jpeg
    - assets/images/BRI.jpeg
    - assets/images/MANDIRI.jpeg
    - assets/images/CC.jpeg
    - assets/images/indomaret.png
    - assets/images/alfamart.png
    - assets/images/verified.jpeg
    - assets/images/type.jpeg
    - assets/images/detail_k1.jpeg
    - assets/images/detail_k2.jpeg
    - assets/images/detail_k3.jpeg
