name: capstone_project_tripease
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  email_validator: ^2.1.17
  flutter:
    sdk: flutter

  google_fonts: ^4.0.4
  introduction_screen: ^3.1.8
  shared_preferences: ^2.1.1

  image_picker: ^0.8.7+5
  flutter_svg: ^2.0.5
  intl: ^0.18.1
  dropdown_button2: ^2.1.2
  dio: ^5.1.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
