name: capstone_project_tripease
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  email_validator: ^2.1.17
  flutter_screenutil: ^5.8.2
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  otp_text_field: ^1.1.3
  image_cropper: ^4.0.1
  image_picker: ^0.8.5+3
  table_calendar: ^3.0.9
  flutter_rating_bar: ^4.0.1
  flutter_datetime_picker: ^1.5.1
  shared_preferences: ^2.1.1
  dropdown_button2: ^2.1.2
  dio: ^5.1.2
  provider: ^6.0.5
  flutter_localization: ^0.1.11
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  get: ^4.6.5
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
